os: osx
sudo: required
language: python
install:
  - curl https://d3f216qdpm0le3.cloudfront.net/ubuntu-16.04-desktop-amd64.iso > ubuntu.iso
  - hdiutil convert -format UDRW -o ubuntu.img ubuntu.iso
addons:
  artifacts: true
